xtest01:
  username: xtest01
  password: A0oX8iipebvaU2OTo07zY9acsFHl1ch%2Bjlb3tbp1RvtD0CTSfUFOwih4A1QspAKOL9q%2B8oOuomMT9nXUBPjGbJRJ5%2BI7R5z946%2BXb5p%2Bxdd%2F0CDvsrlKCU8abkf9HcICyk%2FfHSMShXDEMMzV9eOi8rvZd0JKfbM0lb6tq%2F%2FGnuc%3D

vivi:
  username: vivi
  password: wz8jPsm9QVSSEHW3o6PIczA7IP7zp17aqYFraNdZzGIGHTnHUXPFcg4sv1Z6O0Ch6y%2FvEivnA07CW2KdNkIT%2FeX%2FhSL5SkvZ6AyQRU6GxseTrgsC282USImETAUP1OmTrFXXmG8AASG6B1fa2HkHdqIOEE2DGO7aQ5KZH3ltrLY%3D